services:
  - type: web
    name: smartphone-recommender-fuzzy-mamdani
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.fuzzy_smartphone_mamdani:app --host 0.0.0.0 --port $PORT
